name: ros_tracking
channels:
  - conda-forge
dependencies:
- python==3.10
- pyyaml
- pip
- catkin_pkg
- lark
- pip:
    - pandas==2.1.3
    - pyquaternion==0.9.9
    - nuscenes-devkit==1.1.11
    - motmetrics<=1.1.3
    - matplotlib==3.5.3
    - shapely==1.8.5.post1
    - PySide2
    - empy==3.3.4
    - gtsam==4.2.0