
'human.pedestrian.adult': 'dynamic'
'human.pedestrian.child': 'dynamic'
'human.pedestrian.construction_worker': 'dynamic'
'human.pedestrian.police_officer': 'dynamic'
'human.pedestrian.personal_mobility': 'ackermann'
'movable_object.trafficcone': 'static'
'movable_object.barrier': 'static'
'movable_object.pushable_pullable': 'static'
'movable_object.debris': 'static'
'static_object.bicycle_rack': static
'vehicle.car': 'ackermann'
'vehicle.bicycle': 'ackermann'
'vehicle.truck': 'ackermann'
'vehicle.bus.rigid': 'ackermann'
'vehicle.bus.bendy': 'ackermann'
'vehicle.construction': 'ackermann'
'vehicle.motorcycle': 'ackermann'
'vehicle.trailer': 'ackermann'
'testobject.dynamic': 'dynamic'