# nuscenes_converter:
#   ros__parameters:
    # sensor_type: 'LinearGaussian'
    # sensor_variance: [.25, .25, .1]
    # dim_states: 6
    # dim_meas: 3

compute_nuscenes_node:
  ros__parameters:
    nuscenes_dir: '/home/jd/nuScenes/data'
    mcap_dir: '/home/jd/nuscenes2mcap/mcap'
    results_dir: '/home/jd/tracking_ws/src/ros_tracking/results'
    # dataset_name: 'v1.0-mini'
    split_name: 'mini_val'
    lidar_detector: 'megvii'
    track_topic: 'tracks_scene'
    det_topic: '/detections'

tracker:
  ros__parameters:
    tracker:
      dim_objects: 9
      object_classes: ['void_ignore',
           'bicycle',
           'bus',
           'car',
           'motorcycle',
           'pedestrian',
           'trailer',
           'truck']
      frame_id: 'map'
      asgn_thresh: 4.0
      # trk_timeout: 1.5
      publishers:
        # names: ['track_pub', 'scene_pub']
        names: ['scene_pub']
        # track_pub: # Publisher name
        #   pub_topic: 'tracks'
        #   msg_type: 'Tracks3D'
        #   routine: 'PublishTracks'
        scene_pub: # Publisher name
          pub_topic: 'tracks_scene'
          msg_type: 'SceneUpdate'
          routine: 'PublishScene'

      del_thresh: 0.7
      pub_thresh: 0.6

    sensors:

      #Declare names of sensors upfront
      sensor_names: ['nuscenes-megvii']

      # For each named sensor, give sensor model information
      nuscenes-megvii:
        detector_index: 0
        topic: 'converted_detections'
        msg_type: 'Detections3D'
        
        # Spatial sensor model
        spatial_sensor_model: [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
                0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
                0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
                0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]
        spatial_states: 15
        spatial_meas: 6
        sensor_variance: [.5, .25, .1, .01, .01, .01]

        # Semantic sensor model        
        dim_classes: 8
        dim_detections: 10
        detection_classes: ['barrier',
              'bicycle',
              'bus',
              'car',
              'construction_vehicle',
              'motorcycle',
              'pedestrian',
              'traffic_cone',
              'trailer',
              'truck']
        # p(Z_label|X_class): 
        # columns are dets: missed / barrier / bicycle / bus / car / construction_vehicle / motorcycle / pedestrian / traffic_cone / trailer / truck 
        # semantic_sensor_model: [0.000000, 0.125731, 0.083376, 0.038285, 0.217438, 0.061180, 0.068748, 0.117527, 0.090626, 0.088209, 0.108878, # false_det = nothing there
        #                         0.096489, 0.498358, 0.010609, 0.002273, 0.025006, 0.042182, 0.006062, 0.020965, 0.282900, 0.009598, 0.005557, # void_ignore - barrier, construction_vehicle, traffic cone
        #                         0.089005, 0.047120, 0.586387, 0.005236, 0.062827, 0.000000, 0.036649, 0.120419, 0.000000, 0.010471, 0.041885, # bicycle - 20% missed chance, 5% misclassification chance
        #                         0.390244, 0.000000, 0.000000, 0.476965, 0.021680, 0.010840, 0.000000, 0.000000, 0.000000, 0.016260, 0.084011, # bus
        #                         0.222530, 0.007325, 0.006533, 0.007127, 0.657494, 0.007721, 0.010493, 0.005543, 0.003168, 0.004158, 0.067907, # car
        #                         0.136792, 0.018868, 0.165094, 0.004717, 0.023585, 0.000000, 0.594340, 0.047170, 0.004717, 0.004717, 0.000000, # motorcycle
        #                         0.131802, 0.018594, 0.018868, 0.002461, 0.014766, 0.003828, 0.007383, 0.783976, 0.008750, 0.003828, 0.005742, # pedestrian
        #                         0.150000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.833333, 0.016667, # trailer
        #                         0.198095, 0.011429, 0.000000, 0.009524, 0.196190, 0.011429, 0.000000, 0.007619, 0.000000, 0.005714, 0.560000] # truck
        semantic_sensor_model: [0.498358, 0.010609, 0.002273, 0.025006, 0.042182, 0.006062, 0.020965, 0.282900, 0.009598, 0.005557, # void_ignore - barrier, construction_vehicle, traffic cone
                        0.047120, 0.586387, 0.005236, 0.062827, 0.000000, 0.036649, 0.120419, 0.000000, 0.010471, 0.041885, # bicycle - 20% missed chance, 5% misclassification chance
                        0.000000, 0.000000, 0.476965, 0.021680, 0.010840, 0.000000, 0.000000, 0.000000, 0.016260, 0.084011, # bus
                        0.007325, 0.006533, 0.007127, 0.657494, 0.007721, 0.010493, 0.005543, 0.003168, 0.004158, 0.067907, # car
                        0.018868, 0.165094, 0.004717, 0.023585, 0.000000, 0.594340, 0.047170, 0.004717, 0.004717, 0.000000, # motorcycle
                        0.018594, 0.018868, 0.002461, 0.014766, 0.003828, 0.007383, 0.783976, 0.008750, 0.003828, 0.005742, # pedestrian
                        0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.000000, 0.833333, 0.016667, # trailer
                        0.011429, 0.000000, 0.009524, 0.196190, 0.011429, 0.000000, 0.007619, 0.000000, 0.005714, 0.560000] # truck

        # p_missed_det: 0.30
        # p_false_pos: .60


        #                 void_ignore / bicycle / bus / car / motorcycle / pedestrian / trailer / truck
        p_missed_det_list: [.3, .3, .3, .3, .3, .3, .3, .3]


        #                 barrier / bicycle / bus / car / construction_vehicle / motorcycle / pedestrian / traffic_cone / trailer / truck
        p_false_pos_list: [.6, .6, .6, .6, .6, .6, .6, .6, .6, .6]