nuscenes_converter:
  ros__parameters:
    sensor_type: 'LinearGaussian'
    sensor_variance: [.25, .25, .1]
    dim_states: 6
    dim_meas: 3


tracker:
  ros__parameters:
    sensors:

      #Declare names of sensors upfront
      sensor_names: ['nuscenes-megvii']

      # For each named sensor, give sensor model information
      nuscenes-megvii:
        topic: 'converted_detections'
        msg_type: 'Detections3D'
        # model_type: "position"
        sensor_model: [1., 0., 0., 0., 0., 0.,
                0., 1., 0., 0., 0., 0.,
                0., 0., 1., 0., 0., 0.]
        dim_states: 6
        dim_meas: 3
        sensor_variance: [.25, .25, .1]